### ISSUE TITLE
Error | Update display channel 

### ISSUE THREAD

**Issue by CorentinGS** [yumenetwork/Yume-Bot#27]
Erreur lors de l'update des salons de statistiques sur la guild.

File: event.py
Line : 42

```
bot_1    | Ignoring exception in on_member_join
bot_1    | Traceback (most recent call last):
bot_1    |   File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 270, in _run_event
bot_1    |     await coro(*args, **kwargs)
bot_1    |   File "/usr/src/app/modules/event.py", line 42, in on_member_join
bot_1    |     await channel.delete()
bot_1    |   File "/usr/local/lib/python3.6/site-packages/discord/abc.py", line 510, in delete
bot_1    |     await self._state.http.delete_channel(self.id, reason=reason)
bot_1    |   File "/usr/local/lib/python3.6/site-packages/discord/http.py", line 218, in request
bot_1    |     raise Forbidden(r, data)
bot_1    | discord.errors.Forbidden: 403 FORBIDDEN (error code: 50001): Missing Access
```

Solutions possible :
- vérifier les permissions avant les modifications des salons
- ajouter des exceptions

**Comment by CorentinGS** [comment]
Fixed
